/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */


buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
